import { useEffect, useState } from 'react';
import { BadgeCheck, Plus, Trash2 } from 'lucide-react';
import { toast } from 'sonner';

type Row = { id: number; clientId: number; vehicleId: number | null; type: string; status: string; details: string | null };
type Client = { id: number; name: string };
type Vehicle = { id: number; clientId: number; name: string; plate: string };

export default function HomologationsPage() {
  const [rows, setRows] = useState<Row[]>([]);
  const [clients, setClients] = useState<Client[]>([]);
  const [vehicles, setVehicles] = useState<Vehicle[]>([]);
  const [form, setForm] = useState({ clientId: '', vehicleId: '', type: 'GPS / telemetría', details: '' });
  const load = () => Promise.all([fetch('/api/fleet/homologations', { credentials: 'include' }).then((r) => r.ok ? r.json() : []), fetch('/api/fleet/clients', { credentials: 'include' }).then((r) => r.ok ? r.json() : []), fetch('/api/fleet/vehicles', { credentials: 'include' }).then((r) => r.ok ? r.json() : [])]).then(([a, b, c]) => { setRows(a); setClients(b); setVehicles(c); }).catch(() => {});
  useEffect(() => { load(); }, []);
  const add = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch('/api/fleet/homologations', { method: 'POST', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) { toast.error(data.error || 'No se pudo guardar'); return; } toast.success('Homologación creada'); setForm({ ...form, vehicleId: '', details: '' }); load(); };
  const remove = async (id: number) => { if (!confirm('¿Eliminar esta homologación?')) return; const response = await fetch(`/api/fleet/homologations/${id}`, { method: 'DELETE', credentials: 'include' }); if (response.ok) { toast.success('Homologación eliminada'); load(); } };
  return <div className="space-y-6"><div><h2 className="text-lg font-medium">Homologaciones</h2><p className="text-sm text-muted-foreground mt-1">El usuario técnico puede mantener los requisitos de cada cliente y unidad.</p></div><form onSubmit={add} className="bg-card border border-border rounded-lg p-5 grid grid-cols-1 md:grid-cols-4 gap-3 items-end"><label className="text-sm space-y-2"><span>Cliente</span><select required value={form.clientId} onChange={(e) => setForm({ ...form, clientId: e.target.value, vehicleId: '' })} className="w-full bg-input border border-border rounded-md px-3 py-2 text-sm"><option value="">Selecciona</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label className="text-sm space-y-2"><span>Vehículo</span><select value={form.vehicleId} onChange={(e) => setForm({ ...form, vehicleId: e.target.value })} className="w-full bg-input border border-border rounded-md px-3 py-2 text-sm"><option value="">General</option>{vehicles.filter((vehicle) => String(vehicle.clientId) === form.clientId).map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.plate}</option>)}</select></label><label className="text-sm space-y-2"><span>Tipo</span><input required value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })} className="w-full bg-input border border-border rounded-md px-3 py-2 text-sm" /></label><button className="h-10 rounded-md bg-primary text-primary-foreground text-sm flex items-center justify-center gap-2"><Plus className="w-4 h-4" />Agregar</button></form><div className="bg-card border border-border rounded-lg overflow-hidden"><table className="w-full text-sm"><thead><tr className="border-b border-border bg-muted/20"><th className="px-4 py-3 text-left text-muted-foreground">Tipo</th><th className="px-4 py-3 text-left text-muted-foreground">Cliente</th><th className="px-4 py-3 text-left text-muted-foreground">Unidad</th><th className="px-4 py-3 text-left text-muted-foreground">Estado</th><th className="px-4 py-3 text-right"></th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b border-border/50"><td className="px-4 py-3 flex items-center gap-2"><BadgeCheck className="w-4 h-4 text-primary" />{row.type}</td><td className="px-4 py-3">{clients.find((client) => client.id === row.clientId)?.name || `#${row.clientId}`}</td><td className="px-4 py-3 text-muted-foreground">{vehicles.find((vehicle) => vehicle.id === row.vehicleId)?.plate || 'General'}</td><td className="px-4 py-3">{row.status}</td><td className="px-4 py-3 text-right"><button onClick={() => remove(row.id)} className="text-muted-foreground hover:text-destructive"><Trash2 className="w-4 h-4" /></button></td></tr>)}</tbody></table>{rows.length === 0 && <div className="p-8 text-center text-muted-foreground">No hay homologaciones.</div>}</div></div>;
}