import { useEffect, useState } from 'react';
import { CalendarCheck, Check, Clock3 } from 'lucide-react';
import { toast } from 'sonner';

type Request = { id: number; clientId: number; vehicleId: number | null; scheduledDate: string; timeSlot: string; address: string; notes: string | null; status: string };

export default function InstallationsPage() {
  const [rows, setRows] = useState<Request[]>([]);
  const load = () => fetch('/api/fleet/installation-requests', { credentials: 'include' }).then((r) => r.ok ? r.json() : []).then(setRows).catch(() => {});
  useEffect(() => { load(); }, []);
  const update = async (id: number, status: string) => { const response = await fetch(`/api/fleet/installation-requests/${id}`, { method: 'PATCH', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); if (response.ok) { toast.success('Cita actualizada'); load(); } };
  return <div className="space-y-6"><div><h2 className="text-lg font-medium">Citas técnicas</h2><p className="text-sm text-muted-foreground mt-1">Confirma y da seguimiento a las solicitudes de instalación de clientes.</p></div><div className="grid gap-3">{rows.map((row) => <div key={row.id} className="bg-card border border-border rounded-lg p-5 flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div className="flex items-start gap-3"><div className="p-2 rounded-lg bg-primary/10 text-primary"><CalendarCheck className="w-5 h-5" /></div><div><p className="font-medium">{row.scheduledDate} · {row.timeSlot}</p><p className="text-sm text-muted-foreground">{row.address}</p><p className="text-xs text-muted-foreground mt-1">{row.notes || 'Sin notas'} · Cliente #{row.clientId}</p></div></div><div className="flex items-center gap-2"><span className="text-xs rounded-full border border-primary/30 px-2 py-1 text-primary">{row.status}</span>{row.status === 'requested' && <button onClick={() => update(row.id, 'scheduled')} className="px-3 py-2 text-xs rounded-md bg-primary text-primary-foreground flex gap-1 items-center"><Clock3 className="w-3 h-3" />Confirmar</button>}{row.status === 'scheduled' && <button onClick={() => update(row.id, 'completed')} className="px-3 py-2 text-xs rounded-md bg-green-600 text-white flex gap-1 items-center"><Check className="w-3 h-3" />Completar</button>}</div></div>)}{rows.length === 0 && <div className="bg-card border border-border rounded-lg p-10 text-center text-muted-foreground">No hay citas técnicas pendientes.</div>}</div></div>;
}